### ISSUE TITLE
lesion level evaluation only considers positive lesions? 

### ISSUE THREAD

**Issue by Chacha-Chen** [DIAGNijmegen/picai_eval#16]
Hi, I am using the eval script for a case where we have TN on lesions, which result in lesion results like this
` '11025_1001045': [],
 '10822_1000838': [],` 
in the metric.json.

It follows that in the [this line](https://github.com/DIAGNijmegen/picai_eval/blob/9d0318c2bf00f64296834b872d08ca80429b476f/src/picai_eval/metrics.py#L127), it is not included since the list is empty, which result in all true negative cases not taken into account for lesion level evaluation, is it intended to do so? 

Thank you in advance!

**Comment by joeranbosma** [comment]
Dear @Chacha-Chen,

You are correct, for lesion evaluation the true negative predictions don't come in explicitly. However, it still matters, since it would have been a false positive otherwise. For the lesion-level evaluation of Precision and Recall, you can confirm that the true negative predictions are not taken into account explicitly: https://en.wikipedia.org/wiki/Precision_and_recall

Best,
Joeran

**Comment by Chacha-Chen** [comment]
thanks for clarification!

**Comment by Chacha-Chen** [comment]
Hi just wanna following up on this,
when evaluating AI, we do count true negative lesions since there would be cases where AI gives lesion prediction confidence as for example 0.3, then if we take the threshold of 0.5, this lesion is counted towards a true negative. Am I understanding correctly? 

Thank you so much in advance!

**Comment by joeranbosma** [comment]
Dear @Chacha-Chen,

True negatives are ill-defined in the context of lesion-level evaluation (I could add an arbitrary number of true negatives by adding very small predictions with a very low confidence). That is why you won’t see it appear in the lesion-level evaluation metrics of picai_eval. 
Of course, you can define other metrics, which could include it. 

Best, Joeran
