### ISSUE TITLE
Implementation of evaluation metrics (lesion assignment & patient-level scoring)

### ISSUE THREAD

**Issue by ChristophNeukirchenAtPhilipsCom** [DIAGNijmegen/picai_eval#3]
Dear organizers,
I am trying to understand how the evaluation metrics provided with the python code works (many thanks for implementing and sharing the code). I set it in relation to what is described in the illustrative document [1].

1. Concerning the evaluation of the lesion detection maps:
  - The evaluation metric (i.e. the Average Precision (AP) and the corresponding Precision-Recall (PR) curve) seems to depend on both: i) the confidence level/scores provided in the detection map (dependent in an explicit manner when constructing the PR curve); ii) the size of the detected lesion blobs (dependent in a more implicit manner by disregarding detected blobs with a too low overlap (in terms of IoU) against ground truth). In the function evaluate_case() (in eval.py) a single threshold (default: 0.1) is used to define a "hit criterion". On p.21 of [1] it is suggested to average an evaluation over multiple different thresholds on IuO.
  Does it make sense to extend the evaluation scripts to sweep over a set of thresholds? Or should the AI system get constructed in a way to generate blob sizes in the detection map that are very specifically tailored to the "hit criterion" with a fixed threshold of 0.1 (as this appears useful from a clinical perspective)?
  - In the case of having multiple matching detected blobs and/or multiple ground truth lesions an assignment is done to remove ambiguities between detected and ground truth blobs. On p.22 of [1] it is suggested to either use the "Greedy by Score strategy" or to optimize a cost function (e.g. "Hungarian Matching") to find an optimal assignment. In contrast to that, in the provided code (evaluate_case() in eval.py) the assignment in the case of multiple ground truth lesions looks like: rank the ground truth blobs according to spatial location and make assignments in that order. That can lead to the situation that by flipping or rotation by 180degr. of the ground truth and of the detection map a different assignment is generated compared to the original pose. Is such an assignment suitable in a sense of the evaluation metric.

2. Concerning the evaluation on the patient-level:
  - Do I understand correctly that the participating teams should/may provide an implementation of the function that generates a patient-level scoring (from the detection map) which must be compatible with the interfaces of the evaluation scripts? In that sense, the patient level scores are generated during performing the evaluation?
  - If no function to generate patient-level scores is provided, the evaluation script will pick the maximum confidence value contained anywhere in the detection map as patient score? It does not matter at which spatial location that confidence value occurs (even if it does not match with a ground truth lesion)?

many thanks, 
Christoph

Refs:
[1] Reinke, et al., "Common Limitations of Image Processing Metrics: A Picture Story"

**Comment by joeranbosma** [comment]
Hi @ChristophNeukirchenAtPhilipsCom,

Thanks for your query, those are very good questions!

> The evaluation metric (i.e. the Average Precision (AP) and the corresponding Precision-Recall (PR) curve) seems to depend on both: i) the confidence level/scores provided in the detection map (dependent in an explicit manner when constructing the PR curve); ii) the size of the detected lesion blobs (dependent in a more implicit manner by disregarding detected blobs with a too low overlap (in terms of IoU) against ground truth). In the function evaluate_case() (in eval.py) a single threshold (default: 0.1) is used to define a "hit criterion". On p.21 of [1] it is suggested to average an evaluation over multiple different thresholds on IuO. Does it make sense to extend the evaluation scripts to sweep over a set of thresholds? Or should the AI system get constructed in a way to generate blob sizes in the detection map that are very specifically tailored to the "hit criterion" with a fixed threshold of 0.1 (as this appears useful from a clinical perspective)?

This is a tricky one. We aim to make the evaluation as clinically relevant as possible. Studies on prostate cancer detection in MRI have employed several thresholds, based on several overlap metrics. Recent literature on prostate cancer detection in MRI seems to favour a threshold of 10% ([Duran et al. 2022](https://www.sciencedirect.com/science/article/pii/S1361841521003923?dgcid=rss_sd_all#bib0007), [Baumgartner et al., 2021](https://arxiv.org/abs/2106.00817), [Saha et al., 2021](https://www.sciencedirect.com/science/article/pii/S1361841521002012?via%3Dihub), [Hosseinzadeh et al., 2021](https://link.springer.com/article/10.1007/s00330-021-08320-y)). Please note that the overlap metric varied between studies, so the different thresholds are not exactly the same. Due to the ambiguity in prostate cancer lesion extent and multifocality of lesions, we believe that 10% IoU is a clinically relevant threshold. We aren't aware of a different clinically motivated threshold (such as the 0.05 and 0.5 typical object detection evaluation pipelines use). This is why we chose one threshold, instead of averaging over multiple. If you know a study that motivates a different threshold for clinically significant prostate cancer detection in MRI, please let us know. 

-----

> In the case of having multiple matching detected blobs and/or multiple ground truth lesions an assignment is done to remove ambiguities between detected and ground truth blobs. On p.22 of [1] it is suggested to either use the "Greedy by Score strategy" or to optimize a cost function (e.g. "Hungarian Matching") to find an optimal assignment. In contrast to that, in the provided code (evaluate_case() in eval.py) the assignment in the case of multiple ground truth lesions looks like: rank the ground truth blobs according to spatial location and make assignments in that order. That can lead to the situation that by flipping or rotation by 180degr. of the ground truth and of the detection map a different assignment is generated compared to the original pose. Is such an assignment suitable in a sense of the evaluation metric.

You are completely correct. We did consider the "Greedy by Score" strategy. This strategy matches the highest confidence candidate to the ground truth lesion and discards the other candidate(s). This biases the evaluation to higher scores. Because we also compare AI against [radiologists in the reader study](https://pi-cai.grand-challenge.org/RS/), who do not benefit from this bias, we discarded this strategy and chose to keep the lesion candidate with the highest overlap instead.
Unfortunately, this is implemented in a way where the order of the ground truth lesions can influence the score, which is not the intended behaviour. 
The Hungarian Matching method seems to be an appropriate generalisation of the overlap-based matching we want to apply. I would like to investigate that, do you by any chance have a recommendation for an implementation based on 3D volumes?

-----

> Do I understand correctly that the participating teams should/may provide an implementation of the function that generates a patient-level scoring (from the detection map) which must be compatible with the interfaces of the evaluation scripts? In that sense, the patient level scores are generated during performing the evaluation?

Yes, this is correct! You can define a function with the detection map as input (numpy array of size DxHxW), and the case-level prediction as output (float between 0 and 1). 
During local evaluation this can be achieved by passing your function as ‘case_confidence_func’ (to either [‘evaluate’](https://github.com/DIAGNijmegen/picai_eval#evaluate-individual-detection-maps-with-python) or [‘evaluate_folder’](https://github.com/DIAGNijmegen/picai_eval#evaluate-all-detection-maps-stored-in-a-specific-folder)).
During evaluation on grand-challenge.org, we cannot let users define arbitrary functions for us to evaluate. During deployment, the output of your function must be written to ‘/output/cspca-case-level-likelihood.json’. More documentation on this will follow.

----

> If no function to generate patient-level scores is provided, the evaluation script will pick the maximum confidence value contained anywhere in the detection map as patient score? It does not matter at which spatial location that confidence value occurs (even if it does not match with a ground truth lesion)?

Correct. The case-level confidence must be computable on unseen cases, so it should not depend on the annotation (and thus matching with a ground truth lesion is not taken into account).
